name: termare_view
description: A new Flutter package project.
version: 0.0.3
homepage: https://github.com/termare/termare_view

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.14.13
  quiver: ^3.0.0-nullsafety.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

