name: termare_view
description: 终端模拟器上册组件。
version: 0.0.6
homepage: https://github.com/termare/termare_view

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  # 判断数组相等
  collection: ^1.15.0
  flutter:
    sdk: flutter
  # lrumap
  quiver: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: DroidSansMono
      fonts:
        - asset: assets/fonts/DroidSansMono.ttf
