name: termare_view
description: 终端模拟器上册组件。
version: 0.0.4
homepage: https://github.com/termare/termare_view

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.14.13
  flutter:
    sdk: flutter
  quiver: ^3.0.0-nullsafety.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: DroidSansMono
      fonts:
        - asset: assets/fonts/DroidSansMono.ttf
